/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Withdrawal {
    id: string;
    status: Variant_pending_approved_rejected;
    userName: string;
    userId: Principal;
    date: string;
    withdrawalType: Variant_roi_commission;
    amount: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Investment {
    id: string;
    status: Variant_active_pending_rejected;
    userName: string;
    userId: Principal;
    date: string;
    tier: Variant_blue_black_white;
    certificateId: string;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DownlineMember {
    referralCode: string;
    userId: Principal;
    name: string;
    level: bigint;
}
export interface UserProfile {
    status: Variant_active_pending_inactive;
    directReferrals: bigint;
    packageTier: Variant_blue_none_black_white;
    teamSize: bigint;
    referralCode: string;
    bankAccount?: {
        ifsc: string;
        bankName: string;
        accountNumber: string;
    };
    joinDate: string;
    commissionBalance: bigint;
    name: string;
    email: string;
    roiBalance: bigint;
    totalWithdrawn: bigint;
    uplineCode?: string;
    phone: string;
}
export interface Transaction {
    id: string;
    status: Variant_pending_approved_rejected_credited;
    userId: Principal;
    date: string;
    description: string;
    txType: Variant_roi_commission_withdrawal;
    amount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_pending_inactive {
    active = "active",
    pending = "pending",
    inactive = "inactive"
}
export enum Variant_active_pending_rejected {
    active = "active",
    pending = "pending",
    rejected = "rejected"
}
export enum Variant_blue_black_white {
    blue = "blue",
    black = "black",
    white = "white"
}
export enum Variant_blue_none_black_white {
    blue = "blue",
    none = "none",
    black = "black",
    white = "white"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_pending_approved_rejected_credited {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    credited = "credited"
}
export enum Variant_roi_commission {
    roi = "roi",
    commission = "commission"
}
export enum Variant_roi_commission_withdrawal {
    roi = "roi",
    commission = "commission",
    withdrawal = "withdrawal"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveInvestment(id: string): Promise<Result>;
    approveWithdrawal(id: string): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    creditROI(userId: Principal, amount: bigint, description: string): Promise<Result>;
    getAllInvestments(): Promise<Array<Investment>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAllWithdrawals(): Promise<Array<Withdrawal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyDirectReferrals(): Promise<Array<UserProfile>>;
    getMyDownline(): Promise<Array<DownlineMember>>;
    getMyInvestments(): Promise<Array<Investment>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getMyWithdrawals(): Promise<Array<Withdrawal>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginByEmail(email: string): Promise<UserProfile | null>;
    registerUser(name: string, email: string, phone: string, referralCode: string, uplineCode: string | null): Promise<Result>;
    rejectInvestment(id: string): Promise<Result>;
    rejectWithdrawal(id: string): Promise<Result>;
    requestWithdrawal(amount: bigint, withdrawalType: Variant_roi_commission): Promise<Result>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInvestment(tier: Variant_blue_black_white, amount: bigint, userName: string): Promise<Result>;
    updateMyBankAccount(accountNumber: string, bankName: string, ifsc: string): Promise<Result>;
    updateMyProfile(name: string, email: string, phone: string): Promise<Result>;
    updateUserStatus(userId: Principal, status: Variant_active_pending_inactive): Promise<Result>;
}
import type { Investment as _Investment, Result as _Result, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, Withdrawal as _Withdrawal, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveInvestment(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.approveInvestment(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveInvestment(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveWithdrawal(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async creditROI(arg0: Principal, arg1: bigint, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.creditROI(arg0, arg1, arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditROI(arg0, arg1, arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvestments(): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvestments();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvestments();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDirectReferrals(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDirectReferrals();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDirectReferrals();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDownline(): Promise<Array<DownlineMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDownline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDownline();
            return result;
        }
    }
    async getMyInvestments(): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvestments();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvestments();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawals();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawals();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginByEmail(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginByEmail(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginByEmail(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectInvestment(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectInvestment(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectInvestment(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWithdrawal(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: Variant_roi_commission): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_variant_n38(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_variant_n38(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInvestment(arg0: Variant_blue_black_white, arg1: bigint, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInvestment(to_candid_variant_n43(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInvestment(to_candid_variant_n43(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyBankAccount(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyBankAccount(arg0, arg1, arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyBankAccount(arg0, arg1, arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserStatus(arg0: Principal, arg1: Variant_active_pending_inactive): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, to_candid_variant_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Investment_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Investment): Investment {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Withdrawal_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Withdrawal): Withdrawal {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        ifsc: string;
        bankName: string;
        accountNumber: string;
    }]): {
    ifsc: string;
    bankName: string;
    accountNumber: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        active: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    userName: string;
    userId: Principal;
    date: string;
    tier: {
        blue: null;
    } | {
        black: null;
    } | {
        white: null;
    };
    certificateId: string;
    amount: bigint;
}): {
    id: string;
    status: Variant_active_pending_rejected;
    userName: string;
    userId: Principal;
    date: string;
    tier: Variant_blue_black_white;
    certificateId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n15(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        userId: value.userId,
        date: value.date,
        tier: from_candid_variant_n16(_uploadFile, _downloadFile, value.tier),
        certificateId: value.certificateId,
        amount: value.amount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    } | {
        credited: null;
    };
    userId: Principal;
    date: string;
    description: string;
    txType: {
        roi: null;
    } | {
        commission: null;
    } | {
        withdrawal: null;
    };
    amount: bigint;
}): {
    id: string;
    status: Variant_pending_approved_rejected_credited;
    userId: Principal;
    date: string;
    description: string;
    txType: Variant_roi_commission_withdrawal;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        description: value.description,
        txType: from_candid_variant_n21(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        pending: null;
    } | {
        inactive: null;
    };
    directReferrals: bigint;
    packageTier: {
        blue: null;
    } | {
        none: null;
    } | {
        black: null;
    } | {
        white: null;
    };
    teamSize: bigint;
    referralCode: string;
    bankAccount: [] | [{
            ifsc: string;
            bankName: string;
            accountNumber: string;
        }];
    joinDate: string;
    commissionBalance: bigint;
    name: string;
    email: string;
    roiBalance: bigint;
    totalWithdrawn: bigint;
    uplineCode: [] | [string];
    phone: string;
}): {
    status: Variant_active_pending_inactive;
    directReferrals: bigint;
    packageTier: Variant_blue_none_black_white;
    teamSize: bigint;
    referralCode: string;
    bankAccount?: {
        ifsc: string;
        bankName: string;
        accountNumber: string;
    };
    joinDate: string;
    commissionBalance: bigint;
    name: string;
    email: string;
    roiBalance: bigint;
    totalWithdrawn: bigint;
    uplineCode?: string;
    phone: string;
} {
    return {
        status: from_candid_variant_n25(_uploadFile, _downloadFile, value.status),
        directReferrals: value.directReferrals,
        packageTier: from_candid_variant_n26(_uploadFile, _downloadFile, value.packageTier),
        teamSize: value.teamSize,
        referralCode: value.referralCode,
        bankAccount: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.bankAccount)),
        joinDate: value.joinDate,
        commissionBalance: value.commissionBalance,
        name: value.name,
        email: value.email,
        roiBalance: value.roiBalance,
        totalWithdrawn: value.totalWithdrawn,
        uplineCode: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.uplineCode)),
        phone: value.phone
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    userName: string;
    userId: Principal;
    date: string;
    withdrawalType: {
        roi: null;
    } | {
        commission: null;
    };
    amount: bigint;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    userName: string;
    userId: Principal;
    date: string;
    withdrawalType: Variant_roi_commission;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n32(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        userId: value.userId,
        date: value.date,
        withdrawalType: from_candid_variant_n33(_uploadFile, _downloadFile, value.withdrawalType),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
}): Variant_active_pending_rejected {
    return "active" in value ? Variant_active_pending_rejected.active : "pending" in value ? Variant_active_pending_rejected.pending : "rejected" in value ? Variant_active_pending_rejected.rejected : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blue: null;
} | {
    black: null;
} | {
    white: null;
}): Variant_blue_black_white {
    return "blue" in value ? Variant_blue_black_white.blue : "black" in value ? Variant_blue_black_white.black : "white" in value ? Variant_blue_black_white.white : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    credited: null;
}): Variant_pending_approved_rejected_credited {
    return "pending" in value ? Variant_pending_approved_rejected_credited.pending : "approved" in value ? Variant_pending_approved_rejected_credited.approved : "rejected" in value ? Variant_pending_approved_rejected_credited.rejected : "credited" in value ? Variant_pending_approved_rejected_credited.credited : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roi: null;
} | {
    commission: null;
} | {
    withdrawal: null;
}): Variant_roi_commission_withdrawal {
    return "roi" in value ? Variant_roi_commission_withdrawal.roi : "commission" in value ? Variant_roi_commission_withdrawal.commission : "withdrawal" in value ? Variant_roi_commission_withdrawal.withdrawal : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
}): Variant_active_pending_inactive {
    return "active" in value ? Variant_active_pending_inactive.active : "pending" in value ? Variant_active_pending_inactive.pending : "inactive" in value ? Variant_active_pending_inactive.inactive : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blue: null;
} | {
    none: null;
} | {
    black: null;
} | {
    white: null;
}): Variant_blue_none_black_white {
    return "blue" in value ? Variant_blue_none_black_white.blue : "none" in value ? Variant_blue_none_black_white.none : "black" in value ? Variant_blue_none_black_white.black : "white" in value ? Variant_blue_none_black_white.white : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roi: null;
} | {
    commission: null;
}): Variant_roi_commission {
    return "roi" in value ? Variant_roi_commission.roi : "commission" in value ? Variant_roi_commission.commission : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Investment>): Array<Investment> {
    return value.map((x)=>from_candid_Investment_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Withdrawal>): Array<Withdrawal> {
    return value.map((x)=>from_candid_Withdrawal_n30(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_active_pending_inactive;
    directReferrals: bigint;
    packageTier: Variant_blue_none_black_white;
    teamSize: bigint;
    referralCode: string;
    bankAccount?: {
        ifsc: string;
        bankName: string;
        accountNumber: string;
    };
    joinDate: string;
    commissionBalance: bigint;
    name: string;
    email: string;
    roiBalance: bigint;
    totalWithdrawn: bigint;
    uplineCode?: string;
    phone: string;
}): {
    status: {
        active: null;
    } | {
        pending: null;
    } | {
        inactive: null;
    };
    directReferrals: bigint;
    packageTier: {
        blue: null;
    } | {
        none: null;
    } | {
        black: null;
    } | {
        white: null;
    };
    teamSize: bigint;
    referralCode: string;
    bankAccount: [] | [{
            ifsc: string;
            bankName: string;
            accountNumber: string;
        }];
    joinDate: string;
    commissionBalance: bigint;
    name: string;
    email: string;
    roiBalance: bigint;
    totalWithdrawn: bigint;
    uplineCode: [] | [string];
    phone: string;
} {
    return {
        status: to_candid_variant_n41(_uploadFile, _downloadFile, value.status),
        directReferrals: value.directReferrals,
        packageTier: to_candid_variant_n42(_uploadFile, _downloadFile, value.packageTier),
        teamSize: value.teamSize,
        referralCode: value.referralCode,
        bankAccount: value.bankAccount ? candid_some(value.bankAccount) : candid_none(),
        joinDate: value.joinDate,
        commissionBalance: value.commissionBalance,
        name: value.name,
        email: value.email,
        roiBalance: value.roiBalance,
        totalWithdrawn: value.totalWithdrawn,
        uplineCode: value.uplineCode ? candid_some(value.uplineCode) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_roi_commission): {
    roi: null;
} | {
    commission: null;
} {
    return value == Variant_roi_commission.roi ? {
        roi: null
    } : value == Variant_roi_commission.commission ? {
        commission: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_pending_inactive): {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} {
    return value == Variant_active_pending_inactive.active ? {
        active: null
    } : value == Variant_active_pending_inactive.pending ? {
        pending: null
    } : value == Variant_active_pending_inactive.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_blue_none_black_white): {
    blue: null;
} | {
    none: null;
} | {
    black: null;
} | {
    white: null;
} {
    return value == Variant_blue_none_black_white.blue ? {
        blue: null
    } : value == Variant_blue_none_black_white.none ? {
        none: null
    } : value == Variant_blue_none_black_white.black ? {
        black: null
    } : value == Variant_blue_none_black_white.white ? {
        white: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_blue_black_white): {
    blue: null;
} | {
    black: null;
} | {
    white: null;
} {
    return value == Variant_blue_black_white.blue ? {
        blue: null
    } : value == Variant_blue_black_white.black ? {
        black: null
    } : value == Variant_blue_black_white.white ? {
        white: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
